[2020-06-22 11:23:49,863] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /logout/ HTTP/1.1" 302 0
[2020-06-22 11:23:49,872] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-22 11:23:49,966] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2020-06-22 11:23:49,994] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-22 11:23:52,560] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2020-06-22 11:23:52,626] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-22 11:23:52,780] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-22 11:23:52,912] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:23:58,492] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-summary/ HTTP/1.1" 200 66821
[2020-06-22 11:23:59,275] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 11:23:59,281] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:23:59,289] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:24:02,139] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:24:02,823] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 11:24:02,825] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:24:02,891] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:24:20,212] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 11:24:20,213] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 11:24:20,213] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 11:24:20,312] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 11:24:22,391] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:24:22,602] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 11:24:22,674] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 11:24:22,889] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 11:24:22,891] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 11:24:23,590] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 11:24:23,593] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:24:23,686] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:31:07,299] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:31:07,547] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 11:31:07,605] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 11:31:07,801] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 11:31:07,801] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 11:31:08,375] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 11:31:08,381] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:31:08,480] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:32:40,992] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 11:32:41,215] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 11:32:41,285] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 11:32:41,501] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 11:32:41,502] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 11:32:42,126] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 11:32:42,131] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 842
[2020-06-22 11:32:42,275] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:35:08,157] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 818
[2020-06-22 11:39:37,117] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-22 11:39:37,312] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-22 11:39:37,780] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:39:41,048] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /logout/ HTTP/1.1" 302 0
[2020-06-22 11:39:41,053] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-22 11:39:41,172] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2020-06-22 11:39:41,180] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-22 11:39:42,933] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2020-06-22 11:39:42,983] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-22 11:39:43,171] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-22 11:39:43,317] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:40:03,458] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanSW/TestPlanSW-search/ HTTP/1.1" 200 82301
[2020-06-22 11:40:04,308] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanSW/TestPlanSW-search/?action=first HTTP/1.1" 200 412
[2020-06-22 11:40:04,315] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:40:04,324] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanSW/TestPlanSW-search/ HTTP/1.1" 200 129
[2020-06-22 11:40:06,156] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 11:40:06,166] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 11:40:06,166] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 11:40:06,194] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 11:40:10,067] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanSW/TestPlanSW-search/ HTTP/1.1" 200 2505
[2020-06-22 11:44:45,849] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4872
[2020-06-22 11:45:03,549] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4872
[2020-06-22 11:45:04,947] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 839
[2020-06-22 11:49:38,657] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2020-06-22 11:49:38,797] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1821
[2020-06-22 11:49:38,863] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:49:41,537] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2020-06-22 11:49:41,578] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 20929
[2020-06-22 11:49:41,649] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:50:07,017] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/ HTTP/1.1" 200 16416
[2020-06-22 11:50:07,060] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2020-06-22 11:50:07,140] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:50:27,136] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/16/change/ HTTP/1.1" 200 9002
[2020-06-22 11:50:27,170] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2020-06-22 11:50:27,226] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:50:33,193] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /admin/TestPlanME/testprojectme/16/change/ HTTP/1.1" 302 0
[2020-06-22 11:50:33,298] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/ HTTP/1.1" 200 16608
[2020-06-22 11:50:33,324] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2020-06-22 11:50:33,411] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:50:46,125] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/16/change/ HTTP/1.1" 200 9011
[2020-06-22 11:50:46,150] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2020-06-22 11:50:46,212] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 11:50:49,791] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/ HTTP/1.1" 200 16416
[2020-06-22 11:50:49,889] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 14:09:25,851] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66821
[2020-06-22 14:09:26,152] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 14:09:26,266] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 14:09:26,645] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 14:09:26,646] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 14:09:27,220] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 14:09:27,227] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 863
[2020-06-22 14:09:27,603] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 14:09:30,175] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4872
[2020-06-22 14:09:33,569] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 839
[2020-06-22 14:11:11,737] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 854, in TestPlanME_search
    'Sum': Sums,
UnboundLocalError: local variable 'Sums' referenced before assignment
[2020-06-22 14:11:11,740] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 86631
[2020-06-22 14:11:13,774] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 925
[2020-06-22 14:12:39,238] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:12:41,391] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 925
[2020-06-22 14:14:54,798] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:14:57,975] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 945
[2020-06-22 14:15:37,993] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=0 HTTP/1.1" 200 20188
[2020-06-22 14:17:32,418] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=0 HTTP/1.1" 200 20188
[2020-06-22 14:48:32,651] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66865
[2020-06-22 14:48:32,898] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 14:48:33,012] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 14:48:33,344] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 14:48:33,345] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 14:48:33,844] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 14:48:33,853] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 14:48:33,991] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 14:48:47,994] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=EL571&phase=0 HTTP/1.1" 200 20108
[2020-06-22 14:49:20,506] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:49:21,895] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 954
[2020-06-22 14:49:39,086] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=EL571&phase=0 HTTP/1.1" 200 20108
[2020-06-22 14:51:52,006] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66890
[2020-06-22 14:51:52,330] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 14:51:52,388] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 14:51:52,544] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 14:51:52,545] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 14:51:53,188] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 14:51:53,191] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 14:51:53,337] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 14:51:57,673] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:51:58,550] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 954
[2020-06-22 14:52:08,852] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)-SMB&project=FLV3A&phase=0 HTTP/1.1" 200 1022
[2020-06-22 14:52:13,093] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)-SMB&project=FLV3A&phase=0 HTTP/1.1" 200 1022
[2020-06-22 14:52:24,483] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:52:25,373] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 954
[2020-06-22 14:57:12,395] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66915
[2020-06-22 14:57:12,645] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 14:57:12,695] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 14:57:12,869] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 14:57:12,869] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 14:57:13,495] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 14:57:13,500] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 14:57:13,649] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 14:57:17,335] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:57:18,104] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 954
[2020-06-22 14:57:24,379] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=ELY5U&phase=0 HTTP/1.1" 200 20113
[2020-06-22 14:57:51,840] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 14:57:54,974] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 945
[2020-06-22 14:58:08,604] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=0 HTTP/1.1" 200 20044
[2020-06-22 15:02:21,850] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 15:02:27,014] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 945
[2020-06-22 15:03:03,155] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=0 HTTP/1.1" 200 20044
[2020-06-22 15:03:08,200] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 15:04:43,898] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 15:04:43,908] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 15:04:43,908] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 15:04:43,991] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 15:04:49,198] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66915
[2020-06-22 15:04:49,424] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 15:04:49,477] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 15:04:49,614] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 15:04:49,614] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 15:04:50,148] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 15:04:50,155] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 15:04:50,241] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 15:04:52,914] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 15:04:56,606] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 945
[2020-06-22 15:05:05,035] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=0 HTTP/1.1" 200 20044
[2020-06-22 15:05:10,713] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 15:12:37,283] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/25/change/ HTTP/1.1" 200 9011
[2020-06-22 15:12:37,329] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7684
[2020-06-22 15:12:37,418] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 15:12:40,120] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/TestPlanME/testprojectme/ HTTP/1.1" 200 16416
[2020-06-22 15:12:40,253] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 15:20:35,651] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66897
[2020-06-22 15:20:35,928] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 15:20:36,006] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 15:20:36,350] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 15:20:36,351] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 15:20:36,918] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 15:20:36,922] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 15:20:37,028] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 15:20:40,375] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 15:20:41,318] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1368
[2020-06-22 15:20:49,201] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=EL334&phase=0 HTTP/1.1" 200 20105
[2020-06-22 15:21:07,694] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 15:30:17,708] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 15:30:20,975] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1417
[2020-06-22 15:30:42,498] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4883
[2020-06-22 15:30:43,964] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1426
[2020-06-22 15:31:41,079] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66897
[2020-06-22 15:31:41,406] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 15:31:41,486] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 15:31:41,801] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 15:31:41,802] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 15:31:42,366] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 15:31:42,370] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 15:31:42,479] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 15:31:52,733] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 15:36:04,652] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66861
[2020-06-22 15:36:04,928] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 15:36:05,022] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 15:36:05,411] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 15:36:05,411] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 15:36:05,997] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 15:36:05,999] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 874
[2020-06-22 15:36:06,089] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 15:36:16,107] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLAT4&phase=0 HTTP/1.1" 200 20192
[2020-06-22 15:36:26,485] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 15:36:28,409] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 850
[2020-06-22 16:10:21,157] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'Project' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 931, in TestPlanME_search
    KeypartC38NB.objects.create(**createFFRT)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'Project' cannot be null")
[2020-06-22 16:10:21,170] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 243406
[2020-06-22 16:10:25,586] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66861
[2020-06-22 16:10:25,843] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 16:10:25,894] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 16:10:26,198] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 16:10:26,198] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 16:10:26,750] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 16:10:26,752] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 893
[2020-06-22 16:10:26,878] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 16:10:34,889] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 16:10:36,831] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'Project' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 931, in TestPlanME_search
    KeypartC38NB.objects.create(**createFFRT)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'Project' cannot be null")
[2020-06-22 16:10:36,834] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 243408
[2020-06-22 16:13:04,110] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'Project' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 932, in TestPlanME_search
    KeypartC38NB.objects.create(**createFFRT)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'Project' cannot be null")
[2020-06-22 16:13:04,116] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 243391
[2020-06-22 16:14:15,734] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 933, in TestPlanME_search
    KeyPart = KeypartC38NB.objects.filter(**check_dic_Pro).first()
UnboundLocalError: local variable 'check_dic_Pro' referenced before assignment
[2020-06-22 16:14:15,735] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 81870
[2020-06-22 16:15:16,841] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 956, in TestPlanME_search
    for h in TestProjectME.objects.filter(**check_dic_Pro):
UnboundLocalError: local variable 'check_dic_Pro' referenced before assignment
[2020-06-22 16:15:16,844] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 82174
[2020-06-22 16:15:37,487] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1599
[2020-06-22 16:18:41,043] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66865
[2020-06-22 16:18:41,350] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 16:18:41,460] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 16:18:41,812] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 16:18:41,812] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 16:18:42,354] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 16:18:42,373] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 893
[2020-06-22 16:18:42,691] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 16:18:50,854] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 16:18:52,131] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1599
[2020-06-22 16:18:56,427] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 869
[2020-06-22 16:30:09,915] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1599
[2020-06-22 16:30:13,689] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 1007, in TestPlanME_search
    KeypartC38NB.objects.filter(**dic_Project).update(**updatedic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 689, in update
    query.add_update_values(kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\subqueries.py", line 117, in add_update_values
    field = self.get_meta().get_field(name)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: KeypartC38NB has no field named 'ID'
[2020-06-22 16:30:13,692] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 98108
[2020-06-22 16:36:12,721] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /TestPlanME/TestPlanME-search/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\djangoproject\Reliability_Row_data\TestPlanME\views.py", line 1014, in TestPlanME_search
    KeypartC38NB.objects.filter(**dic_Project).update(**updatedic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 689, in update
    query.add_update_values(kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\subqueries.py", line 117, in add_update_values
    field = self.get_meta().get_field(name)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: KeypartC38NB has no field named 'ID'
[2020-06-22 16:36:12,724] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 500 97983
[2020-06-22 16:36:19,001] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 16:36:19,010] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 16:36:19,011] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 16:36:19,084] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 16:36:20,457] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1599
[2020-06-22 16:36:24,706] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1600
[2020-06-22 16:36:35,022] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1606
[2020-06-22 16:36:40,574] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1607
[2020-06-22 16:36:47,238] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1608
[2020-06-22 16:36:52,106] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1609
[2020-06-22 16:36:57,852] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1610
[2020-06-22 16:37:01,115] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1611
[2020-06-22 16:37:03,788] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1612
[2020-06-22 16:37:09,940] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1613
[2020-06-22 16:37:12,231] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1614
[2020-06-22 16:37:14,804] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1615
[2020-06-22 16:37:19,973] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1616
[2020-06-22 16:37:22,749] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1617
[2020-06-22 16:37:26,919] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1617
[2020-06-22 16:38:07,984] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1618
[2020-06-22 16:38:13,682] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1619
[2020-06-22 16:38:21,017] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1619
[2020-06-22 16:38:40,851] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 16:38:40,921] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 16:38:40,930] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 16:38:40,931] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 16:38:42,677] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66865
[2020-06-22 16:38:42,855] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-22 16:38:42,950] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-22 16:38:43,240] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-22 16:38:43,240] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-22 16:38:43,805] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 893
[2020-06-22 16:38:43,809] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-22 16:38:44,086] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-22 16:38:53,270] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=search&customer=C38(NB)&project=FLMA0&phase=1 HTTP/1.1" 200 20038
[2020-06-22 16:38:55,555] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1619
[2020-06-22 16:39:03,537] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1619
[2020-06-22 16:39:09,650] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1619
[2020-06-22 16:39:13,039] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1619
[2020-06-23 07:56:32,865] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 302 0
[2020-06-23 07:56:33,023] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-23 07:56:42,970] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 302 0
[2020-06-23 07:56:42,973] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-23 07:56:43,125] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2020-06-23 07:56:43,205] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 4677
[2020-06-23 07:56:46,421] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 302 0
[2020-06-23 07:56:46,553] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-23 07:56:46,736] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 34437
[2020-06-23 07:56:47,246] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-23 07:56:50,333] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 66865
[2020-06-23 07:56:51,373] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 893
[2020-06-23 07:56:51,376] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-23 07:56:51,658] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-23 07:56:53,779] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4902
[2020-06-23 07:56:54,883] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1445
[2020-06-23 07:57:09,957] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-summary/ HTTP/1.1" 200 66865
[2020-06-23 07:57:10,672] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /TestPlanME/TestPlanME-search/?action=get HTTP/1.1" 200 803
[2020-06-23 07:57:10,676] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 893
[2020-06-23 07:57:10,940] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 16506
[2020-06-23 07:57:13,893] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4902
[2020-06-23 07:57:24,506] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/lib/bootstrap.min.js.map HTTP/1.1" 404 1806
[2020-06-23 07:57:24,506] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/xlsx/FileSaver.min.js.map HTTP/1.1" 404 1809
[2020-06-23 07:57:24,506] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/js/axios.min.map HTTP/1.1" 404 1773
[2020-06-23 07:57:24,593] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1800
[2020-06-23 07:57:26,979] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4902
[2020-06-23 07:57:40,786] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4902
[2020-06-23 07:57:41,480] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 1450
[2020-06-23 07:59:04,865] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /TestPlanME/TestPlanME-search/ HTTP/1.1" 200 4902
