[2021-11-02 11:15:56,416] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-02 11:22:43,031] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-02 11:23:19,173] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-02 11:23:22,050] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-02 15:31:31,909] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-03 08:24:03,014] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-03 08:47:13,608] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /OBIDeviceResult/OBIDeviceResult_edit/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\OBIDeviceResult\views.py", line 470, in OBIDeviceResult_edit
    if 'SAVE' in str(request.body):
  File "C:\Python372\mecheck\lib\site-packages\django\http\request.py", line 275, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
[2021-11-03 08:47:13,611] [UserIP.py:89] [UserIP:process_response] [CRITICAL]- 系统错误
[2021-11-03 08:47:13,613] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /OBIDeviceResult/OBIDeviceResult_edit/ HTTP/1.1" 500 94561
