[2024-01-18 09:19:19,315] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 199, in index
    return render(request, 'index.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:19:19,335] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /index/ HTTP/1.1" 500 232166
[2024-01-18 09:19:19,527] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 86, in process_request
    return render(request, 'NoPerm.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:19:19,530] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 232599
[2024-01-18 09:36:51,881] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 86, in process_request
    return render(request, 'NoPerm.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:36:51,884] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 232753
[2024-01-18 09:36:52,095] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 86, in process_request
    return render(request, 'NoPerm.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:36:52,097] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 232593
[2024-01-18 09:39:16,617] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\app01\views.py", line 199, in index
    return render(request, 'index.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:39:16,623] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /index/ HTTP/1.1" 500 232166
[2024-01-18 09:39:16,709] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 86, in process_request
    return render(request, 'NoPerm.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:39:16,710] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 232599
[2024-01-18 09:39:41,866] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 86, in process_request
    return render(request, 'NoPerm.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:39:41,868] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 232753
[2024-01-18 09:39:42,079] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1020, in find_library
    return parser.libraries[name]
KeyError: 'notifications_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 86, in process_request
    return render(request, 'NoPerm.html', locals())
  File "C:\Python372\mecheck\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "C:\Python372\mecheck\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1077, in load
    lib = find_library(parser, name)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 1024, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'notifications_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
custom_tag
custom_tag20230828 Non v-pre
custom_tag20230828 Non v-pre horizontal
custom_tagbootstrap20210128
custom_taglinshi
custom_tagvue20210128v_pre
i18n
l10n
log
rest_framework
simpletags
static
staticfiles
tz
[2024-01-18 09:39:42,080] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 232593
